KCFinder_browse:
    path:  /kcfinder/browse.php
    defaults: { _controller: "KCFinderBundle:Proxy:browse" }

KCFinder_css:
    path:  /kcfinder/css/index.php
    defaults: { _controller: "KCFinderBundle:Proxy:css" }

KCFinder_js_localize:
    path:  /kcfinder/js_localize.php
    defaults: { _controller: "KCFinderBundle:Proxy:js_localize" }

KCFinder_upload:
    path:  /kcfinder/upload.php
    defaults: { _controller: "KCFinderBundle:Proxy:upload" }

KCFinder_js_browser_joiner:
    path:  /kcfinder/js/index.php
    defaults: { _controller: "KCFinderBundle:Proxy:js_browser_joiner" }


KCFinder_themes:
    path:  /kcfinder/themes/{theme}/{file}.php
    defaults: { _controller: "KCFinderBundle:Proxy:themes" }

KCFinder_images:
    path:  /kcfinder/themes/{theme}/img/{file}
    defaults: { _controller: "KCFinderBundle:Proxy:img" }
    requirements:
        file: .+